services:
  bot:
    image: capcom6/censor-tg-bot:latest
    environment:
      - TELEGRAM__TOKEN=${TELEGRAM__TOKEN}
      - TELEGRAM__ADMIN_ID=${TELEGRAM__ADMIN_ID}
      - CENSOR__BLACKLIST=${CENSOR__BLACKLIST}
    deploy:
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 8M
