services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM__TOKEN=${TELEGRAM__TOKEN}
      - TELEGRAM__ADMIN_ID=${TELEGRAM__ADMIN_ID}
    restart: unless-stopped
