services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM__TOKEN=${TELEGRAM__TOKEN}
      - TELEGRAM__ADMIN_ID=${TELEGRAM__ADMIN_ID}
      - CENSOR__BLACKLIST=${CENSOR__BLACKLIST}
    restart: unless-stopped
    stop_signal: SIGINT
